[versions]
agp = "9.0.1"
kotlin = "2.3.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"

# JetpackCompose
composeBom = "2026.05.00"
activityCompose = "1.13.0"

# NavigationCompose
navigationCompose = "2.9.8"

# Retrofit
retrofit = "3.0.0"

# Room
room = "2.8.4"

# KotlinXSerialization
kotlinxSerializationJson = "1.11.0"

# Hilt
hilt = "2.59.2"
hiltNavigationCompose = "1.3.0"
ksp = "2.3.7"
material3 = "1.4.0"

# Glide
glideCompose = "1.0.0-beta09"

# JUnit
junit = "4.13.2"

# kotlinx-coroutines-test
coroutines-test = "1.11.0"

# AndroidX Test
androidxTestExtJunit = "1.3.0"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"
junitKtx = "1.3.0"

# AndroidX UI-Test
espresso = "3.7.0"
kaspresso = "1.6.1"
hamcrest = "2.2"

# KoTEA
kotea = "1.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# JetpackCompose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }

# NavigationCompose
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Retrofit
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# KotlinXSerialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Hilt & Hilt Navigation
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

# Glide
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideCompose" }

# JUnit
junit = { group = "junit", name = "junit", version.ref = "junit" }

# kotlinx-coroutines-test
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-test" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }

# AndroidX Test
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

# AndroidX UI-Test
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }
kaspresso-compose-support = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }


# KoTEA
kotea-core = { group = "ru.tinkoff.kotea", name = "core", version.ref = "kotea" }
kotea-android = { group = "ru.tinkoff.kotea", name = "android", version.ref = "kotea" }
kotea-compose = { group = "ru.tinkoff.kotea", name = "compose", version.ref = "kotea" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

# JetpackCompose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# KotlinXSerialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Hilt
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

